<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use DB;
use Str;

class ProductCategorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $categories = [
            'Electronics',
            'Fashion',
            'Home & Kitchen',
            'Books',
            'Beauty & Health',
            'Sports & Outdoors',
            'Toys & Games',
            'Automotive',
            'Jewelry & Accessories',
            'Groceries',
            
            // Bike & Car Accessories
            'Bike Accessories',
            'Car Accessories',
            'Vehicle Performance',
            
            // Mobile & Laptop
            'Mobile Accessories',
            'Laptop Accessories',
            
            // Manufacturing
            'Industrial Equipment',
            'Raw Materials',
            'Electrical Components',
            'Safety Equipment',
            
            // Softwares
            'Operating Systems',
            'Antivirus & Security',
            'Productivity Software',
            'Business & Finance Software',
            'Graphic Design & Multimedia',
            'Development Tools',
            'Cloud Software',
            'Data Management & Analytics',
            'CRM & ERP Software',
            'Project Management Software',
            'Communication & Collaboration Tools',
            'Backup & Recovery Solutions',
            'Video Editing Software',
            'Photo Editing Software',
            '3D Modeling & Animation',
            'CAD Software',
            'AI & Machine Learning Software',
            'Web Development Tools',
            'Mobile App Development Tools',
            'E-commerce Platforms',
            'Gaming Software',
            'Educational Software',
            'Accounting Software',
            'HR & Payroll Software',
            'Marketing Automation Tools',
            'Cybersecurity Tools',
            'Networking Software',
            'Virtualization Software',
            'Cloud Storage Solutions',
            
            // Stationery items
            'Writing Instruments',
            'Notebooks & Journals',
            'Paper & Pads',
            'Files & Folders',
            'Office Supplies',
            'Desk Organizers',
            'Sticky Notes & Memo Pads',
            'Markers & Highlighters',
            'Erasers & Correction Supplies',
            'Staplers & Hole Punches',
            'Scissors & Cutters',
            'Diaries & Planners',
            'Envelopes & Mailing Supplies',
            'Card Holders & Name Tags',
            'Whiteboards & Chalkboards',
            'Labels & Tags',
            'Rulers & Geometry Tools',
            'Glue & Paste',
            'Presentation Supplies',
            'Stamp Pads & Inks',
            'Art Supplies',
            'Textbooks & Reference Books',
            'Calculator',
            'Backpacks & School Bags',
            'Lunch Boxes & Water Bottles',
            'Index Cards',
            'Craft Supplies',
            'Stationery Sets',
            'Tape',
            'Technology & Gadgets',
            'School Uniforms',
            'Science Kits & Experiments',
            'Educational Games & Toys',
            'Calendars & Planners',
            'Chalk & Whiteboard Supplies',
            
            // Foods
            'Fruits & Vegetables',
            'Dairy Products',
            'Meat & Poultry',
            'Seafood',
            'Bakery & Bread',
            'Snacks & Confectionery',
            'Frozen Foods',
            'Canned & Packaged Foods',
            'Grains, Pasta & Noodles',
            'Rice & Pulses',
            'Spices & Condiments',
            'Oils & Ghee',
            'Sauces & Dressings',
            'Breakfast Cereals',
            'Health & Organic Foods',
            'Ready-to-Eat Meals',
            'Baby Food',
            'Nuts & Seeds',
            'Sweets & Desserts',
            'Coffee & Tea',
            'Juices & Soft Drinks',
            'Alcoholic Beverages',
            'Herbs & Seasonings',
            
            // Restaurant items
            'Appetizers & Starters',
            'Main Course',
            'Salads & Sides',
            'Soups & Stews',
            'Beverages',
            'Desserts',
            'Breads & Rotis',
            'Pizzas & Pastas',
            'Burgers & Sandwiches',
            'Rice & Biryani',
            'Noodles & Stir-Fries',
            'Seafood Dishes',
            'Vegetarian Dishes',
            'Non-Vegetarian Dishes',
            'Grilled & Barbecue Items',
            'Fast Food',
            'Combo Meals',
            'Kids Menu',
            'Breakfast Items',
            'Signature Dishes',
            'Vegan & Gluten-Free Options',
            'Healthy & Low-Calorie Meals',
            'Beverage Add-Ons (Mocktails, Shakes)',
            'Sauces & Condiments',
            'Specials & Seasonal Dishes',
            
            // Healthcare products
            'Prescription Medications',
            'Over-the-Counter Medications',
            'Vitamins & Supplements',
            'Personal Care Products',
            'First Aid Supplies',
            'Medical Equipment & Devices',
            'Fitness & Wellness Products',
            'Nutritional Products',
            'Home Healthcare Supplies',
            'Mobility Aids',
            'Incontinence Products',
            'Diabetes Care Products',
            'Respiratory Care Products',
            'Hygiene & Sanitation Products',
            'Skin Care Products',
            'Oral Care Products',
            'Eye Care Products',
            'Hearing Aids & Accessories',
            'Therapeutic Aids',
            'Pain Relief Products',
            'Health Monitors & Trackers',
            'Health & Fitness Books',
            'Medical Accessories',
            'Pet Healthcare Products',
            
            // Toys items
            'Action Figures',
            'Dolls & Dollhouses',
            'Building Blocks & Construction Sets',
            'Arts & Crafts Supplies',
            'Board Games & Puzzles',
            'Educational Toys',
            'Outdoor & Sports Toys',
            'Vehicles & Remote Control Toys',
            'Stuffed Animals & Plush Toys',
            'Electronic Toys',
            'Musical Instruments for Kids',
            'Role Play & Dress Up',
            'Science & Discovery Kits',
            'Kids Books & Activity Sets',
            'Baby Toys',
            'Water Toys',
            'Toy Animals & Figurines',
            'Playsets & Themed Toys',
            'Gift Sets & Party Favors',
            'Wooden Toys',
            'Sensory & Fidget Toys',
            'Collectibles',
            'Seasonal & Holiday Toys',
        
            // Mobile accessories
            'Phone Cases & Covers',
            'Screen Protectors',
            'Chargers & Adapters',
            'Cables & Connectors',
            'Power Banks',
            'Headphones & Earbuds',
            'Bluetooth Speakers',
            'Car Mounts & Holders',
            'Mobile Stands & Holders',
            'Camera Lens Attachments',
            'Memory Cards & Storage',
            'Mobile Gaming Accessories',
            'Smartwatch Bands & Accessories',
            'Wireless Chargers',
            'Portable Speakers',
            'Selfie Sticks',
            'Mobile Cleaning Kits',
            'Data Transfer Devices',
            'Stylus Pens',
            'Travel Accessories',
            'Phone Skins & Decals',
            'Screen Cleaning Solutions',
            'Pop Sockets & Grips',
            
            // Laptop accessories
            'Laptop Bags & Sleeves',
            'External Hard Drives',
            'Laptop Stands & Risers',
            'Cooling Pads',
            'Keyboards & Mice',
            'Webcams',
            'Docking Stations',
            'USB Hubs & Adapters',
            'External Monitors',
            'Headphones & Speakers',
            'Laptop Chargers & Power Adapters',
            'Cable Organizers',
            'Portable Scanners',
            'Laptop Skins & Decals',
            'Laptop Privacy Filters',
            'Microphones',
            'Carrying Cases',
            'Laptop Locks',
            'Cleaning Kits',
            'Portable Projectors',
            'Stylus Pens & Digital Drawing Tablets',
            'Network Adapters & Wi-Fi Extenders',
            
            // Gym products
            'Weightlifting Equipment',
            'Cardio Machines',
            'Resistance Bands',
            'Dumbbells & Barbells',
            'Kettlebells',
            'Medicine Balls',
            'Foam Rollers & Recovery Tools',
            'Gym Apparel',
            'Yoga Mats',
            'Fitness Accessories',
            'Hydration Products',
            'Protein Supplements',
            'Pre-Workout & Energy Supplements',
            'Post-Workout Recovery Products',
            'Fitness Trackers & Smartwatches',
            'Home Gym Equipment',
            'Jump Ropes',
            'Stability Balls',
            'Power Racks & Squat Stands',
            'Gym Bags & Storage',
            
            // Plumbering items
            'Pipes & Fittings',
            'Pipe Wrenches',
            'Plumbing Tapes & Sealants',
            'Drain Cleaners & Uncloggers',
            'Pipe Cutters',
            'Plumbing Valves',
            'Pipe Insulation',
            'Plumbing Hoses',
            'Faucets & Fixtures',
            'Sinks & Basins',
            'Toilets & Bidets',
            'Showerheads & Bath Fittings',
            'Water Heaters & Geysers',
            'Water Pumps',
            'Pipe Clamps & Supports',
            'Plumbing Chemicals',
            'Teflon Tape',
            'Plumbing Tool Kits',
            'Welding Equipment for Pipes',
            'Plumbing Pliers',
            'Water Meters',
            'Backflow Preventers',
            'Plumbing Gauges',
            'Septic Tank Cleaners',
            
            // Carpenter items
            'Hand Saws',
            'Power Drills',
            'Chisels & Gouges',
            'Hammers & Mallets',
            'Measuring Tapes & Rulers',
            'Wood Planers',
            'Sanding Tools',
            'Screws & Nails',
            'Wood Glue & Adhesives',
            'Clamps & Vices',
            'Woodworking Jigs',
            'Saw Blades & Discs',
            'Carpentry Aprons & Gloves',
            'Workbenches & Tables',
            'Carpentry Books & Guides',
            'Marking Tools',
            'Sawhorses & Stands',
            'Woodworking Router Bits',
            'Hand Planes',
            'Wood Carving Tools',
            'Screwdrivers & Bits',
            'Wood Stain & Finishes',
            'Furniture Repair Kits',
            'Woodworking Kits & Sets',
            
            // Entertainment items
            'LED TVs',
            'Soundbars',
            'Home Theater Systems',
            'Streaming Devices',
            'Gaming Consoles',
            'DVD & Blu-ray Players',
            'Speakers & Subwoofers',
            'Projectors',
            'Remote Controls',
            'Virtual Reality Headsets',
            'Headphones & Earbuds',
            'Bluetooth Speakers',
            'Wireless Audio Systems',
            'Music Players & Turntables',
            'Smart Speakers & Voice Assistants',
            'TV Mounts & Stands',
            'Streaming Subscriptions & Services',
            'Video Games',
            'Audio & Video Cables',
            'Media Streaming Devices',
            'Home Automation & Entertainment Control',
            'Entertainment Books & Magazines',
            'Virtual Reality Games',
            'Portable Media Players',
            
            // Electric items
            'Switches & Sockets',
            'Extension Cords',
            'LED Bulbs & Tube Lights',
            'Electrical Wires & Cables',
            'Circuit Breakers & Fuses',
            'Electrical Panels & Boxes',
            'Electrical Tape',
            'Voltage Stabilizers',
            'Inverters & UPS Systems',
            'Generators',
            'Solar Panels & Equipment',
            'Electrical Tools & Testers',
            'Batteries & Chargers',
            'Surge Protectors',
            'Smart Home Devices',
            'Electrical Conduits & Fittings',
            'Power Strips',
            'Transformers & Regulators',
            'Lighting Fixtures',
            'Electricity Meters',
            'Electric Vehicle Chargers',
            'Power Banks & Energy Storage',
            
            // Garden items
            'Gardening Tools',
            'Seeds & Bulbs',
            'Planters & Pots',
            'Garden Decor',
            'Lawn Mowers',
            'Garden Furniture',
            'Watering Cans & Hoses',
            'Fertilizers & Soil',
            'Garden Gloves',
            'Garden Fencing',
            'Weed Control Products',
            'Outdoor Lighting',
            'Bird Feeders & Birdbaths',
            'Greenhouses & Plant Covers',
            'Patio & Deck Accessories',
            'BBQ Grills & Outdoor Cooking',
            'Garden Ornaments',
            'Compost Bins',
            'Garden Irrigation Systems',
            'Pruning & Trimming Tools',
            'Insect & Pest Control',
            'Landscape Design Tools',
            'Plant Stakes & Supports',
            
            // Hardware tools
            'Screwdrivers',
            'Wrenches',
            'Drill Machines',
            'Hammers',
            'Saws',
            'Pliers',
            'Sanding Tools',
            'Ladders',
            'Nails & Screws',
            'Measurement Tools',
            'Gloves',
            'Work Benches',
            'Power Tools',
            'Hardware Tool Sets',
            'Hand Planers',
            'Angle Grinders',
            'Jigsaws',
            'Cutting Tools',
            'Chisels',
            'Tool Storage',
            
            'Security & Surveillance Cameras',
            'Fire Safety Products'
        ];
        
        $categories = array_unique($categories);
        
        foreach ($categories as $category) {
            
            DB::table('product_categories')->insert([
                'name' => $category,
                'slug' => Str::slug($category),
                'created_at' => now(),
            ]);

        }

    }
}
